# Generated by Django 5.2.4 on 2025-07-22 16:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('room_type', models.CharField(choices=[('DM', 'Direct Message'), ('GC', 'Group Chat')], default='DM', editable=False, max_length=50)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
