# Generated by Django 5.2.4 on 2025-08-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_roommodel_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommodel',
            name='code',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
