# Generated by Django 5.2.4 on 2025-08-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_roommodel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommodel',
            name='name',
            field=models.CharField(default='room_name', max_length=255),
            preserve_default=False,
        ),
    ]
